CREATE TABLE IF NOT EXISTS storedsalt (
  id INTEGER PRIMARY KEY CHECK (id = 0),
  salt TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  hashpassword TEXT NOT NULL,
  displayname TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS blogs (
  blogid INTEGER PRIMARY KEY AUTOINCREMENT,
  userid INTEGER NOT NULL,
  author TEXT NOT NULL,
  title TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  lastupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userid) REFERENCES users (userid)
);